language: java
if: branch = master

install:
  - sudo apt-get install -y stardict-tools
  - git clone https://github.com/indic-dict/dict-tools.git ~/dict-tools/ --depth 1

git:
  depth: 1

script: 
  - make all

deploy:      
  provider: pages
  skip_cleanup: false
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: false
